spring.application.name=NotificationEngine

# --- SERVER CONFIG ---
server.port=8080

# --- KAFKA CONFIG ---
# This points to the port we exposed in the docker-compose.yml file
spring.kafka.bootstrap-servers=localhost:9092

# PRODUCER: How Java objects are converted to Kafka data
# We use String for the Key and JSON for the Value (NotificationRequest)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# CONSUMER: How Kafka data is converted back to Java objects
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# TRUSTED PACKAGES:
# Tells it is safe to turn JSON back into your specific class
spring.kafka.consumer.properties.spring.json.trusted.packages=*